# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markown_cache']
    app.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        arguments: ['@app.markdown_transformer']
        #autowire: true
        tags:
            - { name: twig.extension}
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
        #arguments: ['@form.factory', '@doctrine.orm.entity_manager', '@router']
    app.doctrine.has_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        arguments: ['@security.password_encoder']
        tags:
            - {name: doctrine.event_subscriber}
